/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActividadesRouteImport } from './routes/actividades'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as JudoRouteImport } from './routes/judo'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActividadesRoute = ActividadesRouteImport.update({
  id: '/actividades',
  path: '/actividades',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const JudoRoute = JudoRouteImport.update({
  id: '/judo',
  path: '/judo',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/contacto': typeof ContactoRoute
  '/judo': typeof JudoRoute
  '/legal': typeof LegalRoute
  '/noticias': typeof NoticiasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/contacto': typeof ContactoRoute
  '/judo': typeof JudoRoute
  '/legal': typeof LegalRoute
  '/noticias': typeof NoticiasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actividades': typeof ActividadesRoute
  '/contacto': typeof ContactoRoute
  '/judo': typeof JudoRoute
  '/legal': typeof LegalRoute
  '/noticias': typeof NoticiasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actividades'
    | '/contacto'
    | '/judo'
    | '/legal'
    | '/noticias'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actividades'
    | '/contacto'
    | '/judo'
    | '/legal'
    | '/noticias'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/actividades'
    | '/contacto'
    | '/judo'
    | '/legal'
    | '/noticias'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActividadesRoute: typeof ActividadesRoute
  ContactoRoute: typeof ContactoRoute
  JudoRoute: typeof JudoRoute
  LegalRoute: typeof LegalRoute
  NoticiasRoute: typeof NoticiasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actividades': {
      id: '/actividades'
      path: '/actividades'
      fullPath: '/actividades'
      preLoaderRoute: typeof ActividadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judo': {
      id: '/judo'
      path: '/judo'
      fullPath: '/judo'
      preLoaderRoute: typeof JudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActividadesRoute: ActividadesRoute,
  ContactoRoute: ContactoRoute,
  JudoRoute: JudoRoute,
  LegalRoute: LegalRoute,
  NoticiasRoute: NoticiasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
