/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleContactoRouteImport } from './routes/$locale/contacto'
import { Route as LocaleHorariosRouteImport } from './routes/$locale/horarios'
import { Route as LocaleMaestrosRouteImport } from './routes/$locale/maestros'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleContactoRoute = LocaleContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleHorariosRoute = LocaleHorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => LocaleRoute,
} as any)
const LocaleMaestrosRoute = LocaleMaestrosRouteImport.update({
  id: '/maestros',
  path: '/maestros',
  getParentRoute: () => LocaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/contacto': typeof LocaleContactoRoute
  '/$locale/horarios': typeof LocaleHorariosRoute
  '/$locale/maestros': typeof LocaleMaestrosRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/contacto': typeof LocaleContactoRoute
  '/$locale/horarios': typeof LocaleHorariosRoute
  '/$locale/maestros': typeof LocaleMaestrosRoute
  '/$locale': typeof LocaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/$locale/contacto': typeof LocaleContactoRoute
  '/$locale/horarios': typeof LocaleHorariosRoute
  '/$locale/maestros': typeof LocaleMaestrosRoute
  '/$locale/': typeof LocaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/sitemap.xml'
    | '/$locale/contacto'
    | '/$locale/horarios'
    | '/$locale/maestros'
    | '/$locale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/$locale/contacto'
    | '/$locale/horarios'
    | '/$locale/maestros'
    | '/$locale'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/sitemap.xml'
    | '/$locale/contacto'
    | '/$locale/horarios'
    | '/$locale/maestros'
    | '/$locale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/contacto': {
      id: '/$locale/contacto'
      path: '/contacto'
      fullPath: '/$locale/contacto'
      preLoaderRoute: typeof LocaleContactoRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/horarios': {
      id: '/$locale/horarios'
      path: '/horarios'
      fullPath: '/$locale/horarios'
      preLoaderRoute: typeof LocaleHorariosRouteImport
      parentRoute: typeof LocaleRoute
    }
    '/$locale/maestros': {
      id: '/$locale/maestros'
      path: '/maestros'
      fullPath: '/$locale/maestros'
      preLoaderRoute: typeof LocaleMaestrosRouteImport
      parentRoute: typeof LocaleRoute
    }
  }
}

interface LocaleRouteChildren {
  LocaleContactoRoute: typeof LocaleContactoRoute
  LocaleHorariosRoute: typeof LocaleHorariosRoute
  LocaleMaestrosRoute: typeof LocaleMaestrosRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
}

const LocaleRouteChildren: LocaleRouteChildren = {
  LocaleContactoRoute: LocaleContactoRoute,
  LocaleHorariosRoute: LocaleHorariosRoute,
  LocaleMaestrosRoute: LocaleMaestrosRoute,
  LocaleIndexRoute: LocaleIndexRoute,
}

const LocaleRouteWithChildren =
  LocaleRoute._addFileChildren(LocaleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
